INSERT INTO public.pizza (id, nom, prixht, recette, tva100) VALUES (1, 'margarita', 10, 'faire revenir les oignons dans l''huile y ajouter les tomates, ajouter l''ail et le thym', 2);
INSERT INTO public.adresse (id, numero, rue, codepostal, ville) VALUES (1, 20, 'avenue du sentier', 69390, 'Millery');
INSERT INTO public.adresse (id, numero, rue, codepostal, ville) VALUES (2, 10, 'rue du Pont', 69008, 'Lyon');
INSERT INTO public.utilisateur (id, nom, prenom, mot_de_passe, mail) VALUES (1, 'Toto', 'Karine', 'essaidb', 'toto1@gmail.com');
INSERT INTO public.utilisateur (id, nom, prenom, mot_de_passe, mail) VALUES (2, 'Tito', 'Octave', 'ocpizza', 'octave@ocpizza.com');
INSERT INTO public.utilisateur (id, nom, prenom, mot_de_passe, mail) VALUES (3, 'Lino', 'Perrard', 'ocAline', 'lino@ocpizza.com');
INSERT INTO public.client (id, telephone, adresse_id) VALUES (1, 668521484, 1);
INSERT INTO public.client (id, telephone, adresse_id) VALUES (2, 668522545, 2);
INSERT INTO public.panier(id, quantite, id_client, id_pizza) VALUES (1, 2,1, 1);
INSERT INTO public.panier(id, quantite, id_client, id_pizza) VALUES (2, 2,2, 1);
INSERT INTO public.personnel (id, fonction, id_pizzeria) VALUES (1, 'livreur', 1);
INSERT INTO public.personnel (id, fonction, id_pizzeria) VALUES (2, 'accueil', 1);
INSERT INTO public.pizzeria (id, nom, adresse_id) VALUES (1, 'OC Pizza 69', 2);
INSERT INTO public.commande(id, paiement, prixht, tva100, date, etat, id_personnel, id_panier) VALUES (1, true, 20, 4, NULL, 'en commande', 1, 2);
INSERT INTO public.commande(id, paiement, prixht, tva100, date, etat, id_personnel, id_panier) VALUES (2, true, 10, 2, '2020-04-20', 'en commande', 1, 2);
INSERT INTO public.ingredient (id, nom) VALUES (1, 'tomates');
INSERT INTO public.ingredient (id, nom) VALUES (2, 'oignons');
INSERT INTO public.ingredient (id, nom) VALUES (3, 'jambon');
INSERT INTO public.ingredient (id, nom) VALUES (4, 'olive');
INSERT INTO public.ingredient (id, nom) VALUES (5, 'mozzarella');
INSERT INTO public.livraison (id, date, id_client, id_commande) VALUES (1, '2021-04-20', 1, 2);
INSERT INTO public.paiement (id, typepaiement, id_commande, date, paiement) VALUES (1, 'cb', 2, '2021-04-20', true);
INSERT INTO public.pizza_ingredient (id_pizza, id_ingredient, quantite) VALUES (1, 1, 250);
INSERT INTO public.pizza_ingredient (id_pizza, id_ingredient, quantite) VALUES (1, 2, 1);
INSERT INTO public.pizza_ingredient (id_pizza, id_ingredient, quantite) VALUES (1, 3, 2);
INSERT INTO public.pizza_ingredient (id_pizza, id_ingredient, quantite) VALUES (1, 4, 2);
INSERT INTO public.pizza_ingredient (id_pizza, id_ingredient, quantite) VALUES (1, 5, 200);
INSERT INTO public.stock (id_ingredient, id_pizzeria, quantite) VALUES (2, 1, 100);